# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davidfekke/Documents/cplusplus/projects/sslclient

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davidfekke/Documents/cplusplus/projects/sslclient

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.0/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidfekke/Documents/cplusplus/projects/sslclient/CMakeFiles /Users/davidfekke/Documents/cplusplus/projects/sslclient/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davidfekke/Documents/cplusplus/projects/sslclient/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SSLClient.a

# Build rule for target.
SSLClient.a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SSLClient.a
.PHONY : SSLClient.a

# fast build rule for target.
SSLClient.a/fast:
	$(MAKE) -f CMakeFiles/SSLClient.a.dir/build.make CMakeFiles/SSLClient.a.dir/build
.PHONY : SSLClient.a/fast

SSLClient.o: SSLClient.c.o

.PHONY : SSLClient.o

# target to build an object file
SSLClient.c.o:
	$(MAKE) -f CMakeFiles/SSLClient.a.dir/build.make CMakeFiles/SSLClient.a.dir/SSLClient.c.o
.PHONY : SSLClient.c.o

SSLClient.i: SSLClient.c.i

.PHONY : SSLClient.i

# target to preprocess a source file
SSLClient.c.i:
	$(MAKE) -f CMakeFiles/SSLClient.a.dir/build.make CMakeFiles/SSLClient.a.dir/SSLClient.c.i
.PHONY : SSLClient.c.i

SSLClient.s: SSLClient.c.s

.PHONY : SSLClient.s

# target to generate assembly for a file
SSLClient.c.s:
	$(MAKE) -f CMakeFiles/SSLClient.a.dir/build.make CMakeFiles/SSLClient.a.dir/SSLClient.c.s
.PHONY : SSLClient.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SSLClient.a"
	@echo "... SSLClient.o"
	@echo "... SSLClient.i"
	@echo "... SSLClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

